# Generated by Django 5.1.7 on 2025-05-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todos_created_at_alter_todos_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todos',
            options={'ordering': ['deadline']},
        ),
        migrations.AlterField(
            model_name='todos',
            name='deadline',
            field=models.DateField(verbose_name='Data de Entrega'),
        ),
        migrations.AlterField(
            model_name='todos',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
    ]
